name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install pyyaml

      - name: Validate YAML
        run: python -c "import yaml; yaml.safe_load(open('new1.yaml'))"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Copy configuration
        run: scp new1.yaml harshi@172.17.97.144:/etc/config
      - name: Restart SSH service
        run: ssh harshi@172.17.97.144 'systemctl restart ssh.service'
